[project]
name = "persistedstate"
version = "23.6"
description = "Ultra fast persistent store for small states in mapped YAML file"
readme = "README.md"
license = {text = "MIT License"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Utilities",
    "Typing :: Typed",
]
dependencies = ["pyyaml"]

[[project.authors]]
name = "Máté Farkas"
email = "fm@farkas-mate.hu"

[project.urls]
Homepage = "https://github.com/presidento/persistedstate"
Changelog = "https://github.com/presidento/persistedstate/blob/main/CHANGELOG.md"

[tool.setuptools]
package-data = {persistedstate = ["py.typed"]}
